[project]
name = "agent-flow"
version = "0.1.0"
description = "AI驱动的工程实现闭环系统"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[project.scripts]
agent-flow = "main:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
